version: '0.1.{build}'
image: Visual Studio 2017


install:
- docker version

build_script:
- docker build -t sdcharris/win-buildserver .

deploy_script:
- ps: |
    if (!$env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_REPO_BRANCH -eq 'master') {
        docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"
        docker push sdcharris/win-buildserver
    }
